apiVersion: v1
kind: Service
metadata:
    name: "northshoremvp-4642"
    labels:
        app: "northshoremvp-4642"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "northshoremvp-4642"